# Generated by Django 5.2.4 on 2025-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulado", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(max_length=50),
        ),
    ]
