# Generated by Django 5.2.4 on 2025-08-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulado", "0002_alter_usuario_nome"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulado",
            options={
                "ordering": ["tema", "-data_criacao"],
                "verbose_name": "Simulado",
                "verbose_name_plural": "Simulados",
            },
        ),
    ]
