# Generated by Django 5.2.4 on 2025-08-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulado", "0003_alter_simulado_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="assunto",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
