# Generated by Django 5.2.4 on 2025-08-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulado", "0004_questao_assunto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questao",
            options={
                "ordering": ["assunto"],
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
            },
        ),
    ]
